### ISSUE TITLE
[1.21.1] Cannot put Mending/Unbreaking on the armor 

### ISSUE THREAD

**Issue by SkyRunner55** [VeroxUniverse/CrystalChronicles-NeoForge#1]
As the title say we cannot put mending or unbreaking on any of the armor

They work on weapons but not on armor

![2024-12-12_11 06 33](https://github.com/user-attachments/assets/60f7d60b-aadd-4cc6-91c7-ddc1d92a4ef7)

![2024-12-12_11 06 27](https://github.com/user-attachments/assets/ed31bcdf-9ffd-476b-9113-a5ea684b2d5f)

**Comment by SkyRunner55** [comment]
I hope you will see this bug report

**Comment by VeroxUniverse** [comment]
I will look at it. But pls don't spam here thx. I am not every day on github.

**Comment by SkyRunner55** [comment]
> I will look at it. But pls don't spam here thx. I am not every day on github.

sorry for the spam
